kind: Service
apiVersion: v1
metadata:
  name:  mongo-express
spec:
  selector:
    app:  mongo-express
  type:  LoadBalancer
  ports:
  - name:  porty
    port:  8081
    targetPort:  8081
    nodePort: 30000
